a = int(input())
arr= input().split()
b = int(arr[0])
c= int(arr[1])
d= int(arr[2])
e = int(arr[3])

print(1) if a>b else print(0)
print(1) if a>c else print(0)
print(1) if a>d else print(0)
print(1) if a>e else print(0)