arr = input().split()
a = int(arr[0])
b = int(arr[1])

print(1) if a>=b else print(0)
print(1) if a>b else print(0)
print(1) if b>=a else print(0)
print(1) if b>a else print(0)
print(1) if a==b else print(0)
print(1) if a!=b else print(0)